name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  content:  # id of input
    description: 'content of the message'
    required: true
    default: 'Hello world!'
  discord_webhook_url:
    description: 'webhook url of discord channel'
    required: true
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
